from typing import Any, AsyncIterator, TypeVar
from sqlmodel import Session

_T = TypeVar("_T")

class AsyncSession:
    def __init__(self, session: Session): ...
    async def run(self, fn: Any, *args: Any, **kwargs: Any) -> Any: ...
    async def __aenter__(self) -> "AsyncSession": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    async def select(self, *args: Any, **kwargs: Any) -> Any: ...
    async def add(self, obj: Any) -> None: ...
    async def delete(self, obj: Any) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def refresh(self, obj: Any) -> None: ...
    async def get(self, model: Any, obj_id: Any) -> Any: ...
    async def exec(self, *args: Any, **kwargs: Any) -> Any: ...
    async def stream(self, *args: Any, **kwargs: Any) -> AsyncIterator[Any]: ...
